In [1]:
import numpy as np

In [18]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
arr = np.array(lista)

In [6]:
type(arr)

numpy.ndarray

In [20]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[1]

2

In [28]:
arr[0] + arr[5]

7

In [29]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
matriz[0,2]

3

In [37]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [43]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [58]:
arr[-3:]

array([7, 8, 9])

In [59]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [64]:
matriz2 = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
matriz2 = np.array(matriz2)
matriz2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
matriz3 = [[5,6,1], [7,8,8], [1,3,4], [0,3,5]]
matriz3 = np.array(matriz3)
matriz3

array([[5, 6, 1],
       [7, 8, 8],
       [1, 3, 4],
       [0, 3, 5]])

In [74]:
matriz2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
matriz2[0:3:2]

array([[1, 2, 3],
       [7, 8, 9]])

In [75]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr[0:6:2]

array([1, 3, 5])

In [80]:

matriz4 = [[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]], [[19,20,21], [22,23,24], [25,26,27]]]
matriz4 = np.array(matriz4)
matriz4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])