In [1]:
import numpy as np

In [15]:
# Creación de una matriz 2D en NumPy
array_2d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [16]:
print(array_2d.shape)

(2, 3, 3)


In [17]:
print(array_2d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [1]:
import pandas as pd

# DataFrames
df1 = pd.DataFrame([[1, 2], [3, 4]], columns=list('AB'))

In [2]:
df1

A  B
0  1  2
1  3  4